config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :questions do
    resources :answers
  end
  
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?

        can :manage, :all

    else
        can :update, Question do |question|
            question.user == user
        end

        can :destroy, Question do |question|
            question.user == user
        end

        can :destroy, Answer do |answer|
            answer.user == user
        end


        can :create, Question
        can :create, Answer

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(answers_params)
		@answer.user = current_user
		@answer.save

		redirect_to questions_url
	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id]).destroy

		redirect_to questions_url
	end

	private

	def answers_params
		params.require(:answer).permit(:content)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if user_signed_in?
  		redirect_to questions_path
  	end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    authorize! :update, @question
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    authorize! :update, @question
  end

  # POST /questions
  # POST /questions.json
  def create
    @user = current_user
    @question = @user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answer/_answer.html.erb
<p>
	<%= answer.content %>
	  
	   <%= link_to "Delete", question_answer_path(answer.question,answer), method: :delete %>
	  
	   
</p>

app/views/answers/_answer.html.erb
<p>
	<%= answer.content %>
	  <p>by <b><%= answer.user.name %></b></p>
	  <% if can? :destroy, answer %>
	   <%= link_to "Delete", question_answer_path(answer.question,answer), method: :delete %>
	  <% end %> 
	  
	   
</p>

app/views/home/index.html.erb
<h1>It's your forum</h1>
<br>
<h2>Please come Inside</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
       Welcome, <%= current_user.name %>
       <%= link_to "Log out", destroy_user_session_path, method: :delete %>
   <% else %>
       <%= link_to "Sign in", new_user_session_path %>
   <% end %>  

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Forum</h1>
<%= flash[:alert] %>

<%= link_to "New Question", new_question_path %>
<br>
<br>

<% @questions.each do |question| %>

    <div style="border: 1px solid black; background-color: #addbe6;">
      
          <h2> <%= question.content %> </h2>
           <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.name %> 
          <br>
            <% if can? :update, question %>
             <%= link_to "Edit", edit_question_path(question) %>
            <% end %> 
            
            
            <% if can? :destroy, question %>
             <%= link_to "Destroy", question, method: :delete, data: { confirm: 'Are you sure ?' } %>
            <% end %>
            

                   
            <h2>Answers</h2>
            <%= render question.answers %>
              

          <br>
          <p>Add Answers</p>
          <%= form_for([question, question.answers.build]) do |f| %>
              <%= f.text_area :content %>
              <%= submit_tag "Add" %>
          <% end %>    
    </div>

    <br>
    <br>

<% end %>    

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

  <%= link_to 'Edit', edit_question_path(@question) %> |
  
<%= link_to 'Back', questions_path %>